version: '3'
services:
  postgres:
    container_name: postgres_${INSTANCE_NAME}
    image: postgres:13.2
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/docker/zooma_${INSTANCE_NAME}_pgdata:/var/lib/postgresql/data
    networks:
      - docker_local

  zooma-app:
    container_name: zooma_${INSTANCE_NAME}
    build:
      context: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      HUSKY: 0
      POSTGRES_URL: ${POSTGRES_URL}
      PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: always
    volumes:
      - /var/docker/zooma_${INSTANCE_NAME}_appdata:/shared
    networks:
      - docker_local

networks:
  docker_local:
    driver: bridge
