version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:13.2-alpine
    ports:
      - '6543:6543'
    expose:
      - '6543'
    command: -p 6543
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - docker.local

  zooma-app:
    container_name: zooma
    build:
      context: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_URL: ${POSTGRES_URL}
      PORT: 3443
    ports:
      - '3443:3443'
    restart: always
    networks:
      - docker.local

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '7654:80'
    depends_on:
      - postgres
    networks:
      - docker.local

volumes:
  pgadmin-data:

networks:
  docker.local:
    driver: bridge
