version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:13.2
    ports:
      - '6543:6543'
    expose:
      - '6543'
    command: -p 6543
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/docker/zooma_pgdata:/var/lib/postgresql/data
    networks:
      - docker_local

  zooma-app:
    container_name: zooma
    build:
      context: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      HUSKY: 0
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_URL: ${POSTGRES_URL}
      PORT: 3443
    ports:
      - '3443:3443'
    restart: always
    volumes:
      - /var/docker/zooma_appdata:/shared
    networks:
      - docker_local

networks:
  docker_local:
    driver: bridge
