on:
  push:
    branches:
      - dev
      - sdemidov/dev-deploy

name: Yandex Cloud Development deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.ZOOMA_YC_SSH_HOST }}
          PORT: ${{ secrets.ZOOMA_YC_SSH_PORT }}
          USERNAME: ${{ secrets.ZOOMA_YC_SSH_USERNAME }}
          KEY: ${{ secrets.ZOOMA_YC_SSH_KEY }}
        with:
          source: '.'
          target: '/home/ci/zooma_dev'

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.ZOOMA_YC_SSH_HOST }}
          PORT: ${{ secrets.ZOOMA_YC_SSH_PORT }}
          USERNAME: ${{ secrets.ZOOMA_YC_SSH_USERNAME }}
          KEY: ${{ secrets.ZOOMA_YC_SSH_KEY }}
          script: |
            cp .env.dev zooma_dev/.env
            cd zooma_dev
            docker-compose down
            docker-compose up -d --build
            docker system prune --force
